# theme basic info
theme_info:
  name: ILS-X
  version: 1.0.0
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# navigation menu
menu:
  Home: /
  Archives: /archives
  About: /about

# RSS
rss: /atom.xml

# favicon
favicon: images/favicon.png

# comment system
comments:
  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://github.com/xCss/Valine
  valine:
    enable: false
    appid:    # your leancloud application appid
    appkey:   # your leancloud application appkey
    notify: false # mail notifier, https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: 填写昵称和邮箱才能收到回复通知哦~

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: false
  # custom uv span for the whole site
  site_uv: false
  # custom pv span for the whole site
  site_pv: false
  # custom pv span for one page only
  page_pv: false

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false