# theme basic info
theme_info:
  name: ILS
  version: 1.0.0
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# navigation menu
menu:
  Home: /
  Archives: /archives
  About: /about
  # Links: /links
  # ...

# RSS
rss:
  enable: true

# favicon
favicon: images/favicon.png

# comment plugin
comments:
  # Valine.
  # more info please open https://github.com/xCss/Valine
  valine:
    enable: false
    appid:    # your leancloud application appid
    appkey:   # your leancloud application appkey
    notify: false # mail notifier, https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: your placeholder
  
  # Gitalk
  # For more information: https://gitalk.github.io, https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id:     # GitHub repo owner
    repository:    # Repository name to store issues
    client_id:     # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret
    distraction_free_mode: false # Facebook-like distraction free mode

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: false
  # custom uv span for the whole site
  site_uv: false
  # custom pv span for the whole site
  site_pv: false
  # custom pv span for one page only
  page_pv: false

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: false
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

# Code Block
codeblock:
  style: flat  # Available values: default | flat | mac
  copy_button:
    enable: true

# Table of Contents in the Sidebar
# Front-matter variable (unsupport wrap expand_all).
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false
  # Maximum heading depth of generated toc.
  max_depth: 6
